name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

# Hver workflow burde ha minst 1 job! Kan ha flere
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      # Define what action to use ... these are from the actions hub
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12 # Definerer hvilken node version vi vil bruke
      # Kommandoer vi vil action skal kjøre
      - run: npm ci
      - run: npm test
      - run: npm run build
